[package]
name = "chat"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "chat-server"
path = "src/server/server.rs"

[[bin]]
name = "chat-client"
path = "src/client/client.rs"

[dependencies]
sqlx = { version = "0.7.4", features = ["sqlite"] }
